# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField()),
                ('client_name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('zip_code', models.CharField(max_length=9)),
                ('street', models.CharField(max_length=300)),
                ('house_number', models.CharField(max_length=10)),
                ('complement', models.CharField(max_length=500)),
                ('reference_point', models.CharField(max_length=500)),
                ('neighborhood', models.CharField(max_length=200)),
                ('delivery_note', models.TextField()),
                ('delivery_missed_products', models.CharField(choices=[('RC', 'Receive calling to decide'), ('RP', 'Replace missing products with a similar product or price')], default='RC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.IntegerField(choices=[(1, 'Sunday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=1)),
                ('delivery_hours', models.ManyToManyField(to='market.DeliveryHour')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('order_date', models.DateField(auto_now=True)),
                ('was_delivered', models.BooleanField(default=False)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('zip_code', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.CharField(max_length=200)),
                ('minimum_order', models.FloatField()),
                ('delivery_tax', models.FloatField()),
                ('delivery_radius', models.FloatField()),
                ('delivery_times', models.ManyToManyField(to='market.DeliveryTime')),
                ('products', models.ManyToManyField(to='market.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='telephones',
            field=models.ManyToManyField(to='market.Telephone'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='market.ProductType'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Store'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='telephones',
            field=models.ManyToManyField(to='market.Telephone'),
        ),
    ]
