# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytime',
            name='delivery_hours',
        ),
        migrations.RemoveField(
            model_name='store',
            name='delivery_times',
        ),
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
        migrations.AddField(
            model_name='deliveryhour',
            name='delivery_time',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='market.DeliveryTime'),
        ),
        migrations.AddField(
            model_name='deliverytime',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='market.Store'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='market.Store'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_admin',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
