# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20171005_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='market.Product'),
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
