# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20171006_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='telephones',
        ),
        migrations.RemoveField(
            model_name='store',
            name='telephones',
        ),
        migrations.AddField(
            model_name='delivery',
            name='telephone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='telephone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='Telephone',
        ),
    ]
