# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20171006_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryday',
            name='delivery',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_days', to='market.Delivery'),
        ),
        migrations.AlterField(
            model_name='deliveryday',
            name='week_day',
            field=models.IntegerField(choices=[(1, 'Sunday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryhour',
            name='delivery_day',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_hour', to='market.DeliveryDay'),
        ),
    ]
