# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20171007_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('A', 'Approved'), ('S', 'Sent'), ('D', 'Delivered')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_info', to='market.Order'),
        ),
    ]
