# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20171007_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_admin',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
    ]
