# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0013_auto_20171007_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('value', models.FloatField()),
                ('store', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='market.Store')),
            ],
        ),
    ]
