# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20171007_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
